### ISSUE TITLE
Question about /images folder

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/BRAT#1]
Philip,
Would it be best practice for us to always use the `{{ site.baseurl }}/assets/images/ `
folder naming convention instead of the `{{ site.baseurl }}/images/` naming convention? Joe thinks you only need assets folders when in site is hosted inside the `docs` folder, but it seems like it might just be easiest to always use the `assets/images` folder regardless if site is in `docs` folder or in master root?

**Comment by philipbaileynar** [comment]
@lhaycock you should use the `{{ site.baseurl }}/assets/images/` approach in case there are other types of assets that you want to ship with the site later (JavaScript, CSS etc).

I think the Jekyll technology that builds the site just copies everything in the `assets` folder, so technically I don't think you need the images folder. But as I said above... best to nest in an images folder for future-proofing. 

Also, I strongly recommend that whatever strategy you use, you should be consistent across all your sites, jsut so that you don't lose your mind trying to remember which site is which.

**Comment by joewheaton** [comment]
Thanks Pip.
